### PR TITLE
Remove MyPy ignore directive

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by abravalheri** [comment]
Thank you @DimitriPapadopoulos.

Do you know if there is an automatic way of removing directives previously needed by `mypy`? It could be integrated into the CI...

**Comment by DimitriPapadopoulos** [comment]
As a starting point, I suggest some of these [Repo-Review suggestions](
https://learn.scientific-python.org/development/guides/repo-review/?repo=abravalheri%2Fvalidate-pyproject&branch=main) (that's where this PR comes from). I can prepare a PR.

I have no experience with [mypy-upgrade](https://github.com/ugognw/mypy-upgrade).

**Comment by abravalheri** [comment]
> As a starting point, I suggest some of these [Repo-Review suggestions](https://learn.scientific-python.org/development/guides/repo-review/?repo=abravalheri%2Fvalidate-pyproject&branch=main) (that's where this PR comes from). I can prepare a PR.

I think some of these are fine, but others might too much for this repo (like prettier or custom pre-commit message).

Does `mypy-upgrade` can get rid of `type: ignore` comments that become obsolete with newer versions of `mypy`?

**Comment by DimitriPapadopoulos** [comment]
> I think some of these are fine, but others might too much for this repo (like prettier or custom pre-commit message).

I was thinking of the settings related to MyPy only, and then only those that aren't too invasive. See #191.

> Does mypy-upgrade can get rid of type: ignore comments that become obsolete with newer versions of mypy?

Yes, according to [Features](https://github.com/ugognw/mypy-upgrade?tab=readme-ov-file#features):
> * Removal of unused `type: ignore` comments
> * Replacement of blanket `type: ignore` comments with error code-specific comments
> * Support for suppressing multiple mypy errors per-line
> * Preservation of existing in-line comments
> * Optional inclusion of `mypy` error description messages
> * Selective suppression of type errors by file, directory, package, module, or mypy error codes

**Comment by DimitriPapadopoulos** [comment]
Actually, I wonder whether repo-review uses `mypy-upgrade` internally, or if they share a common base. Indeed, they report the exact same issues.

**Comment by henryiii** [comment]
sp-repo-review only looks at configuration files. Generally repo-review plugins are recommended to process configuration files, and aren't encouraged to look at source files. (The WebAssembly version has to fetch each file, so limiting access is encouraged).

**Comment by DimitriPapadopoulos** [comment]
Indeed, I got it all mixed up. I meant that the MyPy changes suggested by repo-review end up in the same suggestions as mypy-update. So the additional MyPy options seem equivalent to mypy-update.

**Pull request merged**
